import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { getStore } from "./blobs-fixture.mjs";
const { copyLaunchWorkspace, ensureProductionLaunch } = await import("../.build/tests/netlify/functions/_shared/launch.js");
const { seal, unseal } = await import("../.build/tests/netlify/functions/_shared/secrets.js");
const { defaultHomepage } = await import("../.build/tests/src/content/homepage.js");
const { render } = await import("../.build/tests/src/entry-server.js");
const originalNetlify = globalThis.Netlify;
const launchKey = randomBytes(32).toString("base64");
globalThis.Netlify = { env: { get: name => name === "Sixteen_Oaks_Secret_Key" ? launchKey : undefined } };
const seed = JSON.parse(await readFile("src/content/seed.json", "utf8"));
const content = structuredClone(seed);
content.projects.push({ ...structuredClone(seed.projects[0]), id: "private-draft", slug: "private-draft", title: "Private launch draft", status: "draft" });
content.homepage = structuredClone(defaultHomepage);
content.homepage.headline = "Saved homepage at launch.";
content.projects[0].cover.src = "/api/media/11111111-1111-4111-8111-111111111111";
content.homepage.heroImage.src = "/api/media/22222222-2222-4222-8222-222222222222";
const mediaKeys = [content.projects[0].cover.src, content.homepage.heroImage.src].map(src => src.replace("/api/", ""));
const source = getStore({ name: "launch-source" });
await source.setJSON("content", content);
const mail = { enabled: true, host: "smtp.example.com", port: 465, username: "owner@example.com", from: "owner@example.com", encryptedPassword: seal("fixture-app-password") };
await source.setJSON("mail", mail);
await source.setJSON("inquiries/test", { message: "Preview test only" });
await source.setJSON("ai-usage/test", { count: 42 });
await source.setJSON("form-key", { key: "preview-signing-key" });
const image = new Uint8Array([1, 2, 3, 4]).buffer;
await source.set(mediaKeys[0], image, { metadata: { contentType: "image/png" } });
const live = getStore({ name: "launch-destination" });

// Missing media must never publish a broken page; retry resumes the frozen snapshot.
await assert.rejects(copyLaunchWorkspace(source, live), /launch image is unavailable/);
assert.equal(await live.get("content"), null);
assert.equal(await live.get("mail"), null);
await source.set(mediaKeys[1], image, { metadata: { contentType: "image/webp" } });
const laterPreview = structuredClone(content);
laterPreview.homepage.headline = "Preview edit after snapshot.";
await source.setJSON("content", laterPreview);
await Promise.all([copyLaunchWorkspace(source, live), copyLaunchWorkspace(source, live)]);
assert.deepEqual(await live.get("content"), content, "All workers use the same snapshot");
assert.deepEqual(await live.get("mail"), mail);
assert.equal(unseal((await live.get("mail")).encryptedPassword), "fixture-app-password");
for (const key of mediaKeys) assert.deepEqual((await live.getWithMetadata(key)).data, image);
assert.equal(await live.get("inquiries/test"), null);
assert.equal(await live.get("ai-usage/test"), null);
assert.equal(await live.get("form-key"), null);
assert.equal(render("/work/private-draft/", await live.get("content")).notFound, true);
const liveEdit = structuredClone(content);
liveEdit.homepage.headline = "New live edit.";
await live.setJSON("content", liveEdit);
await copyLaunchWorkspace(source, live);
assert.deepEqual(await live.get("content"), liveEdit, "Later preview edits never replace live edits");

const existing = getStore({ name: "launch-existing-production" });
await existing.setJSON("content", seed);
await existing.setJSON("mail", { existing: true });
await copyLaunchWorkspace(source, existing);
assert.deepEqual(await existing.get("content"), seed);
assert.deepEqual(await existing.get("mail"), { existing: true });
assert.equal(await existing.get(mediaKeys[0]), null);

const wrongKey = getStore({ name: "launch-wrong-key" });
globalThis.Netlify = { env: { get: () => undefined } };
await assert.rejects(copyLaunchWorkspace(source, wrongKey), /Server setup is incomplete/);
assert.equal(await wrongKey.get("content"), null);
assert.equal(await wrongKey.get("mail"), null);
assert.equal(await wrongKey.get("launch-2026-09-16/snapshot"), null);
// Neither preview requests nor other site IDs may run the launch initializer.
await ensureProductionLaunch({ deploy: { context: "deploy-preview" }, site: { id: "099715b6-036a-40b7-b269-22768604f938" } });
await ensureProductionLaunch({ deploy: { context: "production" }, site: { id: "another-site" } });
globalThis.Netlify = originalNetlify;
const { readContent, storeFor } = await import("../.build/tests/netlify/functions/_shared/store.js");
const productionContext = { deploy: { context: "production", id: "launch-test" }, site: { id: "099715b6-036a-40b7-b269-22768604f938" } };
const previewContext = { deploy: { context: "deploy-preview", id: "launch-source-test" } };
const productionRead = await readContent(productionContext);
assert.deepEqual(productionRead.content, await storeFor(previewContext).get("content", { type: "json" }), "The actual production read triggers the launch from the dedicated preview workspace");
assert.ok(await storeFor(productionContext).get("launch-2026-09-16/complete", { type: "json" }));
assert.deepEqual((await storeFor(productionContext).list({ prefix: "inquiries/" })).blobs, []);
console.log("Passed: one-time production transfer, concurrent starts, interrupted-copy recovery, encrypted mail, referenced images, private drafts, existing-live preservation, and exclusion of test inquiries and counters.");
